- docs/conversion/sakai_12_mysql_conversion.sql
- docs/conversion/sakai_12_oracle_conversion.sql
For https://github.com/sakaiproject/sakai/pull/4674
> SAK-32045 - Change text 'My Workspace' to "Home" in worksite setup

- docs/conversion/sakai_12_oracle_conversion.sql
I don't now if SAM-3346 or LSNBLDR-924 will be merged to 12.x branch that's why I use the "in progress" label. Maybe we could merge this PR and make another one later if those jira's are finally merged into 12.x
> SAK-33889 Fix oracle conversion script.

- docs/conversion/sakai_19_mysql_conversion.sql
- docs/conversion/sakai_19_oracle_conversion.sql
CC: @csev can you look at the LTI changes?
CC: @fostersdesign these Oracle changes are untested....
> SAK-41535 fix Sakai 19 conversion scripts after comparison

- docs/conversion/sakai_19_oracle_conversion.sql
Added all rubrics related tables and constraints from MySQL script.
> SAK-41753 Check Oracle conversion script for Sakai 19

- docs/readme.txt
If you are using https://www.sakailms.org for marketing purposes it should start to show up all over the place.
> #56 update base addresses to this

- docs/conversion/sakai_12_mysql_conversion.sql
- docs/conversion/sakai_12_oracle_conversion.sql
- docs/conversion/sakai_19_mysql_conversion.sql
- docs/conversion/sakai_19_oracle_conversion.sql
1. Remove the bad rbcs perms from Sakai 12
2. Backfill good rubrics perms for Sakai 19
> SAK-40288 fix up Rubric permissions

- docs/conversion/sakai_20_mysql_conversion.sql
- docs/conversion/sakai_20_oracle_conversion.sql
https://jira.sakaiproject.org/browse/SAK-43077
> SAK-43077: NPE for existing gradebooks using categories

- docs/conversion/sakai_20_mysql_conversion.sql
MySQL only. Oracle needs doing and I don't have the chops.
> SAK-43441 Added migration script for forums rubrics

- docs/conversion/sakai_22_mysql_conversion.sql
- docs/conversion/sakai_22_oracle_conversion.sql
https://jira.sakaiproject.org/browse/SAK-40427
Conversion script for existing installations.
> SAK-40427 forums > rename to 'Discussions'

- docs/conversion/sakai_19_5-19_6_mysql_conversion.sql
- docs/conversion/sakai_19_5-19_6_oracle_conversion.sql
- docs/conversion/sakai_20_1-20_2_mysql_conversion.sql
- docs/conversion/sakai_20_1-20_2_oracle_conversion.sql
Will need someone to verify the oracle versions of these scripts
> SAK-44753 Rubrics conversion unique constraint for rubric - tool - item

- docs/conversion/sakai_20_2-20_3_mysql_conversion.sql
- docs/conversion/sakai_20_2-20_3_oracle_conversion.sql
https://jira.sakaiproject.org/browse/SAK-45137
> SAK-45137 rbc_rating update script

- docs/conversion/sakai_20_2-20_3_mysql_conversion.sql
- docs/conversion/sakai_20_2-20_3_oracle_conversion.sql
- docs/conversion/sakai_20_mysql_conversion.sql
- docs/conversion/sakai_20_oracle_conversion.sql
https://jira.sakaiproject.org/browse/SAK-41502
> SAK-41502 Add column GB_GRADING_EVENT_T.IS_EXCLUDED to 20.x scripts

- docs/conversion/sakai_20_mysql_conversion.sql
- docs/conversion/sakai_20_oracle_conversion.sql
https://sakaiproject.atlassian.net/browse/SAK-47205
> SAK-47205 Backfill all existing poll options' order based on their original ID quartz job may cause excessive Garbage Collection

- docs/conversion/sakai_21_3-21_4_mysql_conversion.sql
- docs/conversion/sakai_21_3-21_4_oracle_conversion.sql
- docs/conversion/sakai_22_0-22_1_mysql_conversion.sql
- docs/conversion/sakai_22_0-22_1_oracle_conversion.sql
This is linked to https://github.com/sakaiproject/sakai/pull/10540
> SAK-47291 Conversion scripts for avoiding i18n issues when using external tools in gradebook

- docs/conversion/sakai_23_mysql_conversion.sql
- docs/conversion/sakai_23_oracle_conversion.sql
Conversion script for [#10909](https://github.com/sakaiproject/sakai/pull/10909) >  SAK-47784 Rubrics: Save Rubric as Draft
> SAK-47784 Conversion for Draft Rubrics

- docs/conversion/sakai_23_mysql_conversion.sql
- docs/conversion/sakai_23_oracle_conversion.sql
This is paired with https://github.com/sakaiproject/sakai/pull/10985
> SAK-43542 Conversion for new soft removed date column in assignments

- docs/conversion/s2u_features/S2U-12-mysql.sql
- docs/conversion/s2u_features/S2U-12-oracle.sql
https://sakaiproject.atlassian.net/browse/S2U-12
This is paired with https://github.com/sakaiproject/sakai/pull/11144
> S2U-12 5.1.1.8 Improving i18n and feedback on calculated questions

- docs/conversion/s2u_features/S2U-46-mysql.sql
- docs/conversion/s2u_features/S2U-46-oracle.sql
This is paired with https://github.com/sakaiproject/sakai/pull/11359
> S2U-46 5.3.1 Microsoft: User and Group synchronization

- docs/conversion/s2u_features/S2U-39-mysql.sql
- docs/conversion/s2u_features/S2U-39-oracle.sql
This is paired with https://github.com/sakaiproject/sakai/pull/11340
> S2U-39 rWiki conversion scripts

- docs/conversion/s2u_features/S2U-34-mysql.sql
- docs/conversion/s2u_features/S2U-34-oracle.sql
This is paired with https://github.com/sakaiproject/sakai/pull/11418
> S2U-34 Rubrics conversion scripts

- docs/conversion/s2u_features/S2U-34-mysql.sql
Oracle already allows this (TINYINT) so no script required
> S2U-34 Modification for rubric association column (only mysql)

- docs/conversion/s2u_features/S2U-47-mysql.sql
- docs/conversion/s2u_features/S2U-47-oracle.sql
This is paired with https://github.com/sakaiproject/sakai/pull/11440
> s2u-47 (5.3.2): Meetings tool

- docs/conversion/s2u_features/S2U-32-mysql.sql
- docs/conversion/s2u_features/S2U-32-oracle.sql
This is linked with https://github.com/sakaiproject/sakai/pull/11567
> S2U-32 Assignments: add support for tags

- docs/conversion/s2u_features/S2U-32-S2U-28-mysql.sql
- docs/conversion/s2u_features/S2U-32-S2U-28-oracle.sql
- docs/conversion/s2u_features/S2U-32-mysql.sql
- docs/conversion/s2u_features/S2U-32-oracle.sql
No big changes, just putting together both scripts as we're going to check permissions for the webapi calls and this links both features even more.
> S2U-32 and S2U-28 Tag support for assignments and private messages

- docs/conversion/s2u_features/S2U-39-mysql.sql
- docs/conversion/s2u_features/S2U-39-oracle.sql
This is linked with https://github.com/sakaiproject/sakai/pull/11704
> S2U-39 rWiki conversion scripts update

- docs/conversion/s2u_features/S2U-46-mysql.sql
- docs/conversion/s2u_features/S2U-46-oracle.sql
This is paired with 
https://github.com/sakaiproject/sakai/pull/11710
> S2U-46: Added date columns

- docs/conversion/s2u_features/S2U-32-S2U-28-oracle.sql
https://sakaiproject.atlassian.net/browse/S2U-28
https://sakaiproject.atlassian.net/browse/S2U-32
> S2U-28-32 Fix tags

- docs/conversion/sakai_24_mysql_conversion.sql
- docs/conversion/sakai_24_oracle_conversion.sql
Conversion scripts for: https://github.com/sakaiproject/sakai/pull/12273
https://sakaiproject.atlassian.net/browse/S2U-4
> S2U-4 Microsoft integrations working package - MASTER

- docs/conversion/sakai_22_0-22_1_mysql_conversion.sql
https://sakaiproject.atlassian.net/browse/SAK-50780
> SAK-50780 Oracle: Update Oracle scripts for 22.1

- docs/conversion/sakai_22_1-22_2_oracle_conversion.sql
https://sakaiproject.atlassian.net/browse/SAK-50781
> SAK-50781 Oracle: Update Oracle scripts for 22.2

- docs/conversion/sakai_22_2-22_3_oracle_conversion.sql
https://sakaiproject.atlassian.net/browse/SAK-50782
> SAK-50782 Oracle: Update Oracle scripts for 22.3

- docs/conversion/sakai_22_4-22_5_mysql_conversion.sql
- docs/conversion/sakai_22_4-22_5_oracle_conversion.sql
https://sakaiproject.atlassian.net/browse/SAK-50783
> SAK-50783 Oracle: Update Oracle scripts for 22.5

- docs/conversion/sakai_25_mysql_conversion.sql
- docs/conversion/sakai_25_oracle_conversion.sql
https://sakaiproject.atlassian.net/browse/SAK-50200
> SAK-50200 SCORM - Set default permissions

- docs/conversion/sakai_25_mysql_conversion.sql
- docs/conversion/sakai_25_oracle_conversion.sql
https://sakaiproject.atlassian.net/browse/SAK-50809
> SAK-50809 Oracle: Update Oracle scripts for 25

- docs/conversion/sakai_23_oracle_conversion.sql
Adapting to ORACLE: https://github.com/sakaiproject/sakai-reference/commit/7649b6ae0d8fe270afb29b22df9fc960bdd9b423#diff-9bb1b6c052ea982f7428e7d185c7f7675d26f2b67654bf48934fc8371b89bf9e
```
FILLTMPRBCMAXPOINTS	PROCEDURE	1	4	26	PLS-00103: Se ha encontrado el símbolo "end-of-file" cuando se esperaba uno de los siguientes:
begin function pragma procedure subtype type <an identifier>
<a double-quoted delimited-identifier> current cursor delete
exists prior
ERROR	103
``` 
Any help?
> SAK-47876 Rubrics: Display warning and rubric point value in the association drop-down menu
